server:
  port: 8989
spring:
  data:
    redis:
      prot: 6379
      password: root
      host: 192.168.174.8
      database: 0
      timeout: 100ms
      lettuce:
        pool:
          max-active: 8 #连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
          max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        shutdown-timeout: 100 #关闭超时时间

